### ISSUE TITLE
Production Build failed due to : expected NgxLoadingSpinnerService to have an inner class declaration

### ISSUE THREAD

**Issue by ask9691** [K-Adam/ngx-loading-spinner#6]
Hi
Every things works fine in npm run build on local system. but while push code to Vercel and automatic deployment its failed and gives me following errors.

`16:48:16.663  
WARNING in Invalid constructor parameter decorator in /vercel/529b1f16/node_modules/@k-adam/ngx-loading-spinner/fesm2015/k-adam-ngx-loading-spinner.js:`

`16:48:16.663  
 () => []`

`16:48:16.664  
ERROR in getInternalNameOfClass() called on a non-ES5 class: expected NgxLoadingSpinnerService to have an inner class declaration
16:48:16.738  
npm ERR! code ELIFECYCLE
16:48:16.738  
npm ERR! errno 1`

**Comment by K-Adam** [comment]
Hi!

I was not able to reproduce the error locally, but based on the warning, I suspect that the constructor of `NgxLoadingSpinnerService` is causing it.

I published a new version `1.10.2`, where I eliminated the constructor. Could you please give it a try?

**Comment by nandakola** [comment]
ERROR in getInternalNameOfClass() called on a non-ES5 class: expected NgxLoadingSpinnerService to have an inner class declaration

**Comment by ask9691** [comment]
@K-Adam  I tried But while compile time still facing same error.

ERROR in getInternalNameOfClass() called on a non-ES5 class: expected NgxLoadingSpinnerService to have an inner class declaration

My Dependencies are 
"dependencies": {
    "@angular/animations": "^9.1.9",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "9.0.6",
    "@angular/compiler": "9.0.6",
    "@angular/core": "9.0.6",
    "@angular/forms": "9.0.6",
    "@angular/platform-browser": "9.0.6",
    "@angular/platform-browser-dynamic": "9.0.6",
    "@angular/router": "9.0.6",
    "@k-adam/ngx-loading-spinner": "1.10.2",
    "@ngui/map": "0.30.3",
    "@types/googlemaps": "3.39.3",
    "animate.css": "3.7.0",
    "arrive": "2.4.1",
    "bootstrap": "3.3.7",
    "bootstrap-notify": "3.1.3",
    "chart.js": "^2.9.3",
    "chartist": "0.11.0",
    "core-js": "2.6.9",
    "googleapis": "33.0.0",
    "jquery": "3.4.1",
    "perfect-scrollbar": "1.4.0",
    "primeflex": "^1.1.1",
    "primeicons": "^4.0.0",
    "primeng": "^9.1.0",
    "prismjs": "1.15.0",
    "rxjs": "6.5.4",
    "rxjs-compat": "6.5.4",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.900.6",
    "@angular/cli": "9.0.6",
    "@angular/compiler-cli": "9.0.6",
    "@types/jasmine": "3.5.9",
    "@types/node": "13.9.0",
    "codelyzer": "5.2.1",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-cli": "2.0.0",
    "karma-jasmine": "3.1.1",
    "karma-jasmine-html-reporter": "1.5.2",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "protractor": "5.4.3",
    "ts-node": "8.6.2",
    "tslint": "6.1.0",
    "typescript": "3.7.5"
  }

**Comment by ask9691** [comment]
Hello ,

Solved this problem by changing in tsconfig file.
I changed  "target": "es5" to "target": "es2015" and problem is solved

Thank You
